FROM python:3.11-bullseye
ENV PYTHONBUFFERED=1
WORKDIR /registration
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . . /registration/
CMD [ "python3", "manage.py", "runserver","0.0.0.0:8000"]
